name: Send .coverage to Codecov
on: [push]
jobs:
  run:
    runs-on: windows-latest
    env:
      OS: windows-latest
      PYTHON: '3.7.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7.7
    - name: Generate coverage report
      run: |
        pip install coverage
        pip install pytest-cov
        coverage run main.py --branch
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      
